#!/usr/bin/env python3
"""Write extension/config.js from the bridge config — on any OS.

The original was a bash script, which is exactly the sort of thing that makes a
project "mac only" for no good reason: this step is three lines of string
formatting and it is required before the extension can connect at all.

    python3 bridge/gen_ext_config.py          # or py -3 on Windows

Creates the config file with a fresh random token if there isn't one yet, so a
new machine is one command away from working.
"""
from __future__ import annotations

import json
import os
import secrets
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import config  # noqa: E402


def ensure_config() -> dict:
    path = config.CONFIG_PATH
    data = {}
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            data = {}
    changed = False
    if not data.get("token"):
        data["token"] = secrets.token_hex(24)
        changed = True
        print("生成了新 token")
    if not data.get("port"):
        data["port"] = 8790
        changed = True
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        try:
            path.chmod(0o600)          # a no-op on Windows, which is fine
        except OSError:
            pass
    return data


def main() -> int:
    data = ensure_config()
    out = HERE.parent / "extension" / "config.js"
    out.write_text(
        "// Auto-generated by bridge/gen_ext_config.py — holds the shared token.\n"
        "// Regenerate after changing the token or port. Keep out of git.\n"
        f'export const BRIDGE_WS = "ws://127.0.0.1:{data["port"]}/ws/ext";\n'
        f'export const BRIDGE_TOKEN = "{data["token"]}";\n',
        encoding="utf-8")
    print(f"写入 {out}")
    print(f"配置 {config.CONFIG_PATH}  端口 {data['port']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
